build:
  nodes:
    coverage:
      dependencies:
        after:
          - command: npm run build
      tests:
        before:
          - command: node node_modules/http-server-spa/server build index.html 8082 &
        override:
          - command: npm test
