language: node_js

node_js:
    - "node"
    - "10"
    - "8"
    - "6"

sudo: false

git:
    submodules: false

env:
    global:
        - MOZ_HEADLESS=1

addons:
    firefox: "68.1"

install:
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-linux64.tar.gz
    - mkdir geckodriver
    - tar -xzf geckodriver-v0.25.0-linux64.tar.gz -C geckodriver
    - export PATH=$PATH:$PWD/geckodriver
    - npm install

before_script:
    - npm run build
    - node node_modules/http-server/bin/http-server -p 8082 build

script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov
